//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Tb_Admin
{
    public int Id { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
}

public partial class Tb_Data
{
    public int Id { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Gender { get; set; }
    public string Name { get; set; }
    public string Age { get; set; }
    public string Religion { get; set; }
    public string Mother_Tongue { get; set; }
    public string Country { get; set; }
    public string State { get; set; }
    public string city { get; set; }
    public string Marital_Status { get; set; }
    public string Your_Community { get; set; }
    public string Education_Level { get; set; }
    public string Occupation { get; set; }
    public string Income { get; set; }
    public string Diet { get; set; }
    public string Smoke { get; set; }
    public string Drink { get; set; }
    public string Height { get; set; }
    public string Body_Type { get; set; }
    public string Skin_Tone { get; set; }
    public string Mobile_No { get; set; }
    public string Profile { get; set; }
    public string Image { get; set; }
    public string Username { get; set; }
    public string About { get; set; }
    public string Description { get; set; }
    public string Father { get; set; }
    public string Mother { get; set; }
    public string Sister { get; set; }
    public string Brother { get; set; }
    public string Family_Income { get; set; }
    public string Stay { get; set; }
    public string Family_Value { get; set; }
}
